import ctypes

class constants():

    PI: int = None
    RAD_TO_DEG: int = None
    DEG_TO_RAD: int = None
    RADIAN: int = None
    RADIUS: int = None
    OMEGA: int = None
    GRAV: int = None
    SECONDS_PER_DAY: int = None
    SECONDS_PER_HOUR: int = None
    SECONDS_PER_MINUTE: int = None
    RADGAS: int = None
    RVGAS: int = None
    HLV: int = None
    HLS: int = None
    KAPPA: int = None
    CP_AIR: int = None
    CP_VAPOR: int = None
    CP_OCEAN: int = None
    DENS_H20: int = None
    RHOAIR: int = None
    RHO0: int = None
    RHO0R: int = None
    RHO_CP: int = None
    O2MIXRAT: int = None
    WTMAIR: int = None
    WTMH2O: int = None
    WTMOZONE: int = None
    WTMC: int = None
    WTMCO2: int = None
    WTMCH4: int = None
    WTMO2: int = None
    WTMCFC11: int = None
    WTMCFC12: int = None
    WTMN: int = None
    DIFFAC: int = None
    ES0: int = None
    PSTD: int = None
    PSTD_MKS: int = None
    KELVIN: int = None
    TFREEZE: int = None
    C2DBARS: int = None
    STEFAN: int = None
    AVOGNO: int = None
    VONKARM: int = None
    ALOGMIN: int = None
    EPSLN: int = None
    RADCON: int = None
    RADCON_MKS: int = None
    
    def __init__(self, cFMS: ctypes.CDLL = None):
        self.cFMS = cFMS
        self.PI = ctypes.c_double.in_dll(self.cFMS, "PI")
        self.RAD_TO_DEG = ctypes.c_double.in_dll(self.cFMS, "RAD_TO_DEG")
        self.DEG_TO_RAD = ctypes.c_double.in_dll(self.cFMS, "DEG_TO_RAD")
        self.RADIAN = ctypes.c_double.in_dll(self.cFMS, "RADIAN")
        self.RADIUS = ctypes.c_double.in_dll(self.cFMS, "RADIUS")
        self.OMEGA = ctypes.c_double.in_dll(self.cFMS, "OMEGA")
        self.GRAV = ctypes.c_double.in_dll(self.cFMS, "GRAV")
        self.SECONDS_PER_DAY = ctypes.c_double.in_dll(self.cFMS, "SECONDS_PER_DAY")
        self.SECONDS_PER_HOUR = ctypes.c_double.in_dll(self.cFMS, "SECONDS_PER_HOUR")
        self.SECONDS_PER_MINUTE = ctypes.c_double.in_dll(self.cFMS, "SECONDS_PER_MINUTE")
        self.RADGAS = ctypes.c_double.in_dll(self.cFMS, "RDGAS")
        self.RVGAS = ctypes.c_double.in_dll(self.cFMS, "RVGAS")
        self.HLV = ctypes.c_double.in_dll(self.cFMS, "HLV")
        self.HLS = ctypes.c_double.in_dll(self.cFMS, "HLS")
        self.KAPPA = ctypes.c_double.in_dll(self.cFMS, "KAPPA")
        self.CP_AIR = ctypes.c_double.in_dll(self.cFMS, "CP_AIR")
        self.CP_VAPOR = ctypes.c_double.in_dll(self.cFMS, "CP_VAPOR")
        self.CP_OCEAN = ctypes.c_double.in_dll(self.cFMS, "CP_OCEAN")
        self.DENS_H20 = ctypes.c_double.in_dll(self.cFMS, "DENS_H20")
        self.RHOAIR = ctypes.c_double.in_dll(self.cFMS, "RHOAIR")
        self.RHO0 = ctypes.c_double.in_dll(self.cFMS, "RHO0")
        self.RHO0R = ctypes.c_double.in_dll(self.cFMS, "RHO0R")
        self.RHO_CP = ctypes.c_double.in_dll(self.cFMS, "RHO_CP")
        self.O2MIXRAT = ctypes.c_double.in_dll(self.cFMS, "O2MIXRAT")
        self.WTMAIR = ctypes.c_double.in_dll(self.cFMS, "WTMAIR")
        self.WTMH2O = ctypes.c_double.in_dll(self.cFMS, "WTMH2O")
        self.WTMOZONE = ctypes.c_double.in_dll(self.cFMS, "WTMOZONE")
        self.WTMC = ctypes.c_double.in_dll(self.cFMS,  "WTMC")
        self.WTMCO2 = ctypes.c_double.in_dll(self.cFMS, "WTMCO2")
        self.WTMCH4 = ctypes.c_double.in_dll(self.cFMS, "WTMCH4")
        self.WTMO2 = ctypes.c_double.in_dll(self.cFMS, "WTMO2")
        self.WTMCFC11 = ctypes.c_double.in_dll(self.cFMS, "WTMCFC11")
        self.WTMCFC12 = ctypes.c_double.in_dll(self.cFMS, "WTMCFC12")
        self.WTMN = ctypes.c_double.in_dll(self.cFMS, "WTMN")
        self.DIFFAC = ctypes.c_double.in_dll(self.cFMS, "DIFFAC")
        self.ES0 = ctypes.c_double.in_dll(self.cFMS, "ES0")
        self.PSTD = ctypes.c_double.in_dll(self.cFMS, "PSTD") 
        self.PSTD_MKS = ctypes.c_double.in_dll(self.cFMS, "PSTD_MKS")
        self.KELVIN = ctypes.c_double.in_dll(self.cFMS, "KELVIN")
        self.TFREEZE = ctypes.c_double.in_dll(self.cFMS, "TFREEZE")
        self.C2DBARS = ctypes.c_double.in_dll(self.cFMS, "C2DBARS")
        self.STEFAN = ctypes.c_double.in_dll(self.cFMS, "STEFAN")
        self.AVOGNO = ctypes.c_double.in_dll(self.cFMS, "AVOGNO")
        self.VONKARM = ctypes.c_double.in_dll(self.cFMS, "VONKARM")
        self.ALOGMIN = ctypes.c_double.in_dll(self.cFMS, "ALOGMIN")
        self.EPSLN = ctypes.c_double.in_dll(self.cFMS, "EPSLN")
        self.RADCON = ctypes.c_double.in_dll(self.cFMS, "RADCON")
        self.RADCON_MKS = ctypes.c_double.in_dll(self.cFMS, "RADCON_MKS")


        
